spring:
  application:
    name: NovelServiceApplication
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
#  security:
#    user:
#      name: test
#      password: test
  hibernate:
    ddl-auto: none
  jpa:
    show-sql: true


apiPrefix: /api

#KOREAN
server:
  servlet:
    encoding:
      force-response: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-in-seconds: 7_200
  refresh-token-validity-in-seconds: 1_209_600

#server:
#  port: 80
