-- MEMBER_AUTHORITY
DROP TABLE IF EXISTS `MEMBER_AUTHORITY`;
-- MEMBER_COIN_HISTORY
DROP TABLE IF EXISTS `MEMBER_COIN_HISTORY`;
-- CONTENT_COIN_HISTORY
DROP TABLE IF EXISTS `CONTENT_COIN_HISTORY`;
-- NOVEL_TITLE_CONTENT
DROP TABLE IF EXISTS `TITLE_CONTENT`;

DROP TABLE IF EXISTS `MEMBER`;
DROP TABLE IF EXISTS `LOGIN_HISTORY`;
DROP TABLE IF EXISTS `COIN`;
DROP TABLE IF EXISTS `TITLE`;
DROP TABLE IF EXISTS `IMAGE`;
DROP TABLE IF EXISTS `CONTENT`;
DROP TABLE IF EXISTS `COIN_HISTORY`;