-- MEMBER_AUTHORITY
DROP TABLE IF EXISTS `MEMBER_AUTHORITY`;

CREATE TABLE `MEMBER_AUTHORITY` (
    `MEMBER_ID`    BIGINT  NOT NULL,
    `AUTHORITY_NAME` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`MEMBER_ID`, `AUTHORITY_NAME`)
);

-- MEMBER_COIN_HISTORY
DROP TABLE IF EXISTS `MEMBER_COIN_HISTORY`;

CREATE TABLE `MEMBER_COIN_HISTORY` (
    `MEMBER_ID` BIGINT NOT NULL,
    `COIN_HISTORY_ID` BIGINT NOT NULL,
    PRIMARY KEY (`MEMBER_ID`, `COIN_HISTORY_ID`)
);

-- CONTENT_COIN_HISTORY
DROP TABLE IF EXISTS `CONTENT_COIN_HISTORY`;

CREATE TABLE `CONTENT_COIN_HISTORY` (
    `CONTENT_ID` BIGINT NOT NULL,
    `COIN_HISTORY_ID` BIGINT NOT NULL,
    PRIMARY KEY (`CONTENT_ID`, `COIN_HISTORY_ID`)
);


-- NOVEL_TITLE_CONTENT
DROP TABLE IF EXISTS `TITLE_CONTENT`;

CREATE TABLE `TITLE_CONTENT` (
    `TITLE_ID` BIGINT NOT NULL,
    `CONTENT_ID` BIGINT NOT NULL,
    PRIMARY KEY (`TITLE_ID`, `CONTENT_ID`)
);